channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - autopep8
  - jupyter
  - pylint
  - pytest
  - pdoc3
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - scipy
  - pandas
  - joblib
  - pytorch
  - pip:
    - argparse
    - deap
    - opencv-python
    - scoop
    - update_checker
    - tqdm
    - stopit
    - xgboost
    - tpot
